### ISSUE TITLE
Residential areas missing

### ISSUE THREAD

**Issue by Gazer75** [Mathias-S/kartverket2osm#2]
Seems residential areas are missing in converted files.
Comparing the lua files the only difference I can find is that in the sosi files this is "Tettbebyggelse" while lua files specifies Tett**B**ebyggelse".
Could this be enough to throw it off?

**Comment by NKAmapper** [comment]
Seems to be correct, "Tettbebyggelse" with lowercase b: https://objektkatalog.geonorge.no/Objekttype/Index/EAID_267265DD_465D_41c5_9EF0_3B093810A682

**Comment by Mathias-S** [comment]
Fixed with pull request #1. Thanks!
