### ISSUE TITLE
New file names from Kartverket break .sh files

### ISSUE THREAD

**Issue by Gazer75** [Mathias-S/kartverket2osm#3]
Not sure what section needs modification, but affected files are parseArea.sh, parseCoast.sh and parseWater.sh

Today file names are in this format:
Basisdata_0427_Elverum_25833_N50Kartdata_SOSI.zip
Basisdata_0427_Elverum_25833_N50Arealdekke_SOSI.sos

**Comment by Mathias-S** [comment]
Fixed with pull request #4. Thanks for all the help in the IRC channel!
