### ISSUE TITLE
Flytte til osmno?

### ISSUE THREAD

**Issue by NKAmapper** [Mathias-S/kartverket2osm#6]
Hei, kunne du tenke deg å flytte hele kartverket2osm til osmno?

Det er behov for å gjøre noen endringer nå, og best å "originalen" ett sted uten for mange forks.

**Comment by Mathias-S** [comment]
Ja, vet ikke hvorfor jeg ikke har gjort det tidligere. Har gjort det nå. Bare å gjøre endringer! 😄

**Comment by ghost** [comment]
🎉
